In [21]:
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
import pandas
import os
import numpy as np

import sklearn.preprocessing as preprocessing
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error


def calcrae(p, a):
    suma = 0.0
    for i in range(len(p)):
        suma += a[i]
    ave = suma/len(p)
    f1 = f2 = 0.0
    for i in range(len(p)):
        # f1+=abs(p[i]-a[i])
        # f2+=abs(ave-a[i])
        f1 += (p[i]-a[i])*(p[i]-a[i])
        f2 += (ave-a[i])*(ave-a[i])
    return (f1**0.5)/(f2**0.5)


dataframe = pandas.read_csv("./lable.csv", header=0)
dataset = dataframe.values
dim = 61
datas = dataset[0:, 1:dim+1].astype('float')
labels = dataset[0:, dim+1].astype('float')
names = dataset[0:, 0]
print(datas)
print(labels)

x_train = datas
y_train = labels
# scaler = preprocessing.MinMaxScaler()
scaler =preprocessing.StandardScaler()
x_train = scaler.fit_transform(x_train)

# x_val = x_train[0:255]
# partial_x_train = x_train[255:]
# y_val = y_train[0:255]
# partial_y_train = y_train[255:]
x_val, partial_x_train, y_val, partial_y_train = train_test_split(
    x_train, y_train, test_size=0.2, random_state=42)

reg = RandomForestRegressor(random_state=42)
reg.fit(x_val, y_val)

result = reg.predict(partial_x_train)
for i in range(len(result)):
    print("%s %.2f %d" % (names[i], result[i], partial_y_train[i]))
print(r2_score(partial_y_train, result))
print(mean_squared_error(partial_y_train, result))
print(mean_absolute_error(partial_y_train, result))
print(calcrae(partial_y_train, result))



[[ 0.  0.  0. ...  0.  5. 29.]
 [ 0.  0.  0. ...  0.  5. 50.]
 [ 0.  0.  0. ...  0.  0.  0.]
 ...
 [ 0.  0.  0. ...  0. 11. 11.]
 [ 0.  0.  0. ...  0.  0.  0.]
 [ 0.  0.  0. ...  0.  0.  0.]]
[ 42.  74. 100.   8.   4.   8.  10.   8.  50.  88.  91.  47.   4.   1.
 170.  41.   2.  32.   9.   2.  48.   0.   0.   0.   1.   2.  22.   3.
   6.  15.  12.  95.  13.   1.  10.   8.   9.   2.   2.  11.   2.  57.
   9.   0.  25.   2. 948.   4.   4.  10.  20.   4.   4.   0.   0.   6.
   2.   1. 102.  34.   0.  80. 276.   1.  61.   4.  78.   2. 130.  14.
  20.  19.   4.  10. 229.  37.   1.   2.   2.   1.   1.   1.   1.   1.
   0. 200.  51.   0.  49.  48.  69.   1.   1.   1.   1.  90.   0. 123.
 220.   4.   1.  43.  44.   0.   0.   1.   0.   4.  68.  21.  35.   9.
   9.   2.  72.  48.  37.   3.   3. 104.   8.   6.  71.   1.   1.   1.
   1.   1.   1.   1.   1.   1.   3.   1.  22.   1.   1.   2.  43.  13.
   0.  90.  15.  17.  17.  34.  27.  16.  21.  21.  15.   0.   3. 157.
  15.   1.  10.   0.   0.  